部分ui中的javascript错误不应该破坏整个应用程序，

为了解决React用户的这个问题， React16引入了一个错误边界的新概念。

错误边界是一个组件，这个组件可以用来捕捉它子组件中产生的错误， 

记录错误日志并在错误发生的时候， 展示一个回退或者错误信息页面，而不至于整个程序崩掉

错误边界可以捕获其子组件的渲染、生命周期以及构造函数内的错误， （可接受所有子组件的错误信息， 并不继续冒泡）

原则上， 只用于保证ui输出，而不用真的用来捕捉异常

自react 16 起，所有未被捕捉的错误将会卸载整个React组件树

主要是使用componentDidCatch钩子函数

下面的实现，还是会报错导致整个程序崩快， 结合最新版的Suspense （可用来实现同步网络请求并渲染），可以实现

```jsx
import React,{Component} from 'react';

class ErrorBoundary extends Component{
  constructor(){
        super();
        this.state = {hasErrors:false};
  }
  //此生命周期函数可以用来捕获错误和信息
  componentDidCatch(err,info){
      if(err){
        this.setState({
            hasErrors:true
        });
      }
  }
  render(){
    if(this.state.hasErrors){
        return <div>子组件发生未知错误，无法正常显示</div>
    }
    return this.props.children;
  }
}
function Clock(){
    console.log(null.toString());
    return <div style={{border:'5px solid green',padding:'5px'}}>{Date.now()}</div>
}
function Counter(){
    return <div style={{border:'5px solid blue',padding:'5px'}}>计数器</div>
}
export default class Page extends Component{
    render(){
        return (
            <div style={{border:'5px solid red',padding:'5px'}}>
                page
                <ErrorBoundary>
                    <Clock/>
                </ErrorBoundary>
                <Counter/>
            </div>
           
        )
    }
}
```

